/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeacherCoursesIndexRouteImport } from './routes/teacher/courses/index'
import { Route as AdminUniversitiesIndexRouteImport } from './routes/admin/universities/index'
import { Route as AdminTeachersIndexRouteImport } from './routes/admin/teachers/index'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as TeacherCoursesCourseIdIndexRouteImport } from './routes/teacher/courses/$courseId/index'
import { Route as AdminUniversitiesUniversityIdIndexRouteImport } from './routes/admin/universities/$universityId/index'
import { Route as AdminTeachersTeacherIdIndexRouteImport } from './routes/admin/teachers/$teacherId/index'
import { Route as AdminStudentsStudentIdIndexRouteImport } from './routes/admin/students/$studentId/index'
import { Route as AdminUniversitiesUniversityIdCollegeIdIndexRouteImport } from './routes/admin/universities/$universityId/$collegeId/index'
import { Route as AdminUniversitiesUniversityIdCollegeIdDepartmentIdIndexRouteImport } from './routes/admin/universities/$universityId/$collegeId/$departmentId/index'
import { Route as AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdIndexRouteImport } from './routes/admin/universities/$universityId/$collegeId/$departmentId/$levelId/index'
import { Route as AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdCourseIdIndexRouteImport } from './routes/admin/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId/index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TeacherCoursesIndexRoute = TeacherCoursesIndexRouteImport.update({
  id: '/teacher/courses/',
  path: '/teacher/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUniversitiesIndexRoute = AdminUniversitiesIndexRouteImport.update({
  id: '/universities/',
  path: '/universities/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeachersIndexRoute = AdminTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TeacherCoursesCourseIdIndexRoute =
  TeacherCoursesCourseIdIndexRouteImport.update({
    id: '/teacher/courses/$courseId/',
    path: '/teacher/courses/$courseId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUniversitiesUniversityIdIndexRoute =
  AdminUniversitiesUniversityIdIndexRouteImport.update({
    id: '/universities/$universityId/',
    path: '/universities/$universityId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminTeachersTeacherIdIndexRoute =
  AdminTeachersTeacherIdIndexRouteImport.update({
    id: '/teachers/$teacherId/',
    path: '/teachers/$teacherId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminStudentsStudentIdIndexRoute =
  AdminStudentsStudentIdIndexRouteImport.update({
    id: '/students/$studentId/',
    path: '/students/$studentId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUniversitiesUniversityIdCollegeIdIndexRoute =
  AdminUniversitiesUniversityIdCollegeIdIndexRouteImport.update({
    id: '/universities/$universityId/$collegeId/',
    path: '/universities/$universityId/$collegeId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUniversitiesUniversityIdCollegeIdDepartmentIdIndexRoute =
  AdminUniversitiesUniversityIdCollegeIdDepartmentIdIndexRouteImport.update({
    id: '/universities/$universityId/$collegeId/$departmentId/',
    path: '/universities/$universityId/$collegeId/$departmentId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdIndexRoute =
  AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdIndexRouteImport.update(
    {
      id: '/universities/$universityId/$collegeId/$departmentId/$levelId/',
      path: '/universities/$universityId/$collegeId/$departmentId/$levelId/',
      getParentRoute: () => AdminRouteRoute,
    } as any,
  )
const AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdCourseIdIndexRoute =
  AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdCourseIdIndexRouteImport.update(
    {
      id: '/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId/',
      path: '/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId/',
      getParentRoute: () => AdminRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/teachers': typeof AdminTeachersIndexRoute
  '/admin/universities': typeof AdminUniversitiesIndexRoute
  '/teacher/courses': typeof TeacherCoursesIndexRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdIndexRoute
  '/admin/teachers/$teacherId': typeof AdminTeachersTeacherIdIndexRoute
  '/admin/universities/$universityId': typeof AdminUniversitiesUniversityIdIndexRoute
  '/teacher/courses/$courseId': typeof TeacherCoursesCourseIdIndexRoute
  '/admin/universities/$universityId/$collegeId': typeof AdminUniversitiesUniversityIdCollegeIdIndexRoute
  '/admin/universities/$universityId/$collegeId/$departmentId': typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdIndexRoute
  '/admin/universities/$universityId/$collegeId/$departmentId/$levelId': typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdIndexRoute
  '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId': typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/teachers': typeof AdminTeachersIndexRoute
  '/admin/universities': typeof AdminUniversitiesIndexRoute
  '/teacher/courses': typeof TeacherCoursesIndexRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdIndexRoute
  '/admin/teachers/$teacherId': typeof AdminTeachersTeacherIdIndexRoute
  '/admin/universities/$universityId': typeof AdminUniversitiesUniversityIdIndexRoute
  '/teacher/courses/$courseId': typeof TeacherCoursesCourseIdIndexRoute
  '/admin/universities/$universityId/$collegeId': typeof AdminUniversitiesUniversityIdCollegeIdIndexRoute
  '/admin/universities/$universityId/$collegeId/$departmentId': typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdIndexRoute
  '/admin/universities/$universityId/$collegeId/$departmentId/$levelId': typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdIndexRoute
  '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId': typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/teachers/': typeof AdminTeachersIndexRoute
  '/admin/universities/': typeof AdminUniversitiesIndexRoute
  '/teacher/courses/': typeof TeacherCoursesIndexRoute
  '/admin/students/$studentId/': typeof AdminStudentsStudentIdIndexRoute
  '/admin/teachers/$teacherId/': typeof AdminTeachersTeacherIdIndexRoute
  '/admin/universities/$universityId/': typeof AdminUniversitiesUniversityIdIndexRoute
  '/teacher/courses/$courseId/': typeof TeacherCoursesCourseIdIndexRoute
  '/admin/universities/$universityId/$collegeId/': typeof AdminUniversitiesUniversityIdCollegeIdIndexRoute
  '/admin/universities/$universityId/$collegeId/$departmentId/': typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdIndexRoute
  '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/': typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdIndexRoute
  '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId/': typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/'
    | '/teacher'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/universities'
    | '/teacher/courses'
    | '/admin/students/$studentId'
    | '/admin/teachers/$teacherId'
    | '/admin/universities/$universityId'
    | '/teacher/courses/$courseId'
    | '/admin/universities/$universityId/$collegeId'
    | '/admin/universities/$universityId/$collegeId/$departmentId'
    | '/admin/universities/$universityId/$collegeId/$departmentId/$levelId'
    | '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/teacher'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/universities'
    | '/teacher/courses'
    | '/admin/students/$studentId'
    | '/admin/teachers/$teacherId'
    | '/admin/universities/$universityId'
    | '/teacher/courses/$courseId'
    | '/admin/universities/$universityId/$collegeId'
    | '/admin/universities/$universityId/$collegeId/$departmentId'
    | '/admin/universities/$universityId/$collegeId/$departmentId/$levelId'
    | '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/'
    | '/teacher/'
    | '/admin/students/'
    | '/admin/teachers/'
    | '/admin/universities/'
    | '/teacher/courses/'
    | '/admin/students/$studentId/'
    | '/admin/teachers/$teacherId/'
    | '/admin/universities/$universityId/'
    | '/teacher/courses/$courseId/'
    | '/admin/universities/$universityId/$collegeId/'
    | '/admin/universities/$universityId/$collegeId/$departmentId/'
    | '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/'
    | '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherCoursesIndexRoute: typeof TeacherCoursesIndexRoute
  TeacherCoursesCourseIdIndexRoute: typeof TeacherCoursesCourseIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/teacher/courses/': {
      id: '/teacher/courses/'
      path: '/teacher/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/universities/': {
      id: '/admin/universities/'
      path: '/universities'
      fullPath: '/admin/universities'
      preLoaderRoute: typeof AdminUniversitiesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/teachers/': {
      id: '/admin/teachers/'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/teacher/courses/$courseId/': {
      id: '/teacher/courses/$courseId/'
      path: '/teacher/courses/$courseId'
      fullPath: '/teacher/courses/$courseId'
      preLoaderRoute: typeof TeacherCoursesCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/universities/$universityId/': {
      id: '/admin/universities/$universityId/'
      path: '/universities/$universityId'
      fullPath: '/admin/universities/$universityId'
      preLoaderRoute: typeof AdminUniversitiesUniversityIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/teachers/$teacherId/': {
      id: '/admin/teachers/$teacherId/'
      path: '/teachers/$teacherId'
      fullPath: '/admin/teachers/$teacherId'
      preLoaderRoute: typeof AdminTeachersTeacherIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students/$studentId/': {
      id: '/admin/students/$studentId/'
      path: '/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminStudentsStudentIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/universities/$universityId/$collegeId/': {
      id: '/admin/universities/$universityId/$collegeId/'
      path: '/universities/$universityId/$collegeId'
      fullPath: '/admin/universities/$universityId/$collegeId'
      preLoaderRoute: typeof AdminUniversitiesUniversityIdCollegeIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/universities/$universityId/$collegeId/$departmentId/': {
      id: '/admin/universities/$universityId/$collegeId/$departmentId/'
      path: '/universities/$universityId/$collegeId/$departmentId'
      fullPath: '/admin/universities/$universityId/$collegeId/$departmentId'
      preLoaderRoute: typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/': {
      id: '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/'
      path: '/universities/$universityId/$collegeId/$departmentId/$levelId'
      fullPath: '/admin/universities/$universityId/$collegeId/$departmentId/$levelId'
      preLoaderRoute: typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId/': {
      id: '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId/'
      path: '/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId'
      fullPath: '/admin/universities/$universityId/$collegeId/$departmentId/$levelId/$courseId'
      preLoaderRoute: typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdCourseIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  AdminTeachersIndexRoute: typeof AdminTeachersIndexRoute
  AdminUniversitiesIndexRoute: typeof AdminUniversitiesIndexRoute
  AdminStudentsStudentIdIndexRoute: typeof AdminStudentsStudentIdIndexRoute
  AdminTeachersTeacherIdIndexRoute: typeof AdminTeachersTeacherIdIndexRoute
  AdminUniversitiesUniversityIdIndexRoute: typeof AdminUniversitiesUniversityIdIndexRoute
  AdminUniversitiesUniversityIdCollegeIdIndexRoute: typeof AdminUniversitiesUniversityIdCollegeIdIndexRoute
  AdminUniversitiesUniversityIdCollegeIdDepartmentIdIndexRoute: typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdIndexRoute
  AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdIndexRoute: typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdIndexRoute
  AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdCourseIdIndexRoute: typeof AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdCourseIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  AdminTeachersIndexRoute: AdminTeachersIndexRoute,
  AdminUniversitiesIndexRoute: AdminUniversitiesIndexRoute,
  AdminStudentsStudentIdIndexRoute: AdminStudentsStudentIdIndexRoute,
  AdminTeachersTeacherIdIndexRoute: AdminTeachersTeacherIdIndexRoute,
  AdminUniversitiesUniversityIdIndexRoute:
    AdminUniversitiesUniversityIdIndexRoute,
  AdminUniversitiesUniversityIdCollegeIdIndexRoute:
    AdminUniversitiesUniversityIdCollegeIdIndexRoute,
  AdminUniversitiesUniversityIdCollegeIdDepartmentIdIndexRoute:
    AdminUniversitiesUniversityIdCollegeIdDepartmentIdIndexRoute,
  AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdIndexRoute:
    AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdIndexRoute,
  AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdCourseIdIndexRoute:
    AdminUniversitiesUniversityIdCollegeIdDepartmentIdLevelIdCourseIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherCoursesIndexRoute: TeacherCoursesIndexRoute,
  TeacherCoursesCourseIdIndexRoute: TeacherCoursesCourseIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
