import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { createCollegeSchema, updateCollegeSchema } from "shared";
import { useCollege } from "@/hooks/use-college";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";

interface CollegeDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  college?: any;
  universityId: string;
}

export function CollegeDialog({
  open,
  onOpenChange,
  college,
  universityId,
}: CollegeDialogProps) {
  const isEditing = !!college;
  const { createMutation, updateMutation } = useCollege(1, "", universityId);

  // We need to adhere to the schema expected by the mutation
  // createCollegeSchema requires: id, name, universityId
  // updateCollegeSchema requires: id, name, universityId

  // However, the form itself usually just takes 'name'.
  // The 'universityId' is passed as a prop.
  // The 'id' is generated by backend (or zod expects uuid).
  // Actually, Zod schema in shared often expects all fields.
  // But usually front-end forms use a subset.
  // Let's check shared schema again.
  // It says createCollegeSchema = { id: uuid, name: string, universityId: uuid }
  // This implies the client must send an ID? Or the schema is too strict for incoming payload.
  // Usually for creation payload (DTO), we omit ID.
  // Let's assume the mutation handles it or the schema needs adjustment.
  // But wait, in `use-college.ts`:
  // mutationFn: async (json: { name: string; universityId: string })
  // So the mutation expects `name` and `universityId`.

  // Ref: use-university.ts used `createUniversity` from shared which likely didn't have ID or it was optional?
  // Let's check `university.zod.ts`.
  // createUniversity = { id: uuid, name: string ... }
  // Wait, if the shared schema requires ID, then frontend must gen it or backend validation fails?
  // Usually backend validation hook handles omitting ID?
  // The `zodValidator` middleware validates against the schema.
  // If the schema requires ID, we must send it.
  // But usually we don't send ID for create.

  // Let's look at `UniversityDialog` imports: `createUniversity` from shared.
  // `resolver: zodResolver(isEditing ? updateUniversity : createUniversity)`
  // If `createUniversity` schema requires ID, then form must provide it or fail.
  // So likely I should assume it's fine or I need to check schemas.
  // I'll stick to simple form with name.

  const form = useForm({
    resolver: zodResolver(
      isEditing
        ? updateCollegeSchema.omit({ id: true, universityId: true }) // Validation only for editable fields
        : createCollegeSchema.omit({ id: true, universityId: true }),
    ),
    // Actually, simple object is safer if schemas are strict:
    // resolver: zodResolver(z.object({ name: z.string().min(1) })),
    defaultValues: {
      name: college?.name || "",
    },
  });

  // Reset form when opening/closing or changing college
  useEffect(() => {
    if (open) {
      form.reset({
        name: college?.name || "",
      });
    }
  }, [open, college, form]);

  const onSubmit = (values: any) => {
    const options = {
      onSuccess: () => {
        onOpenChange(false);
        form.reset();
      },
    };

    if (isEditing && college) {
      updateMutation.mutate(
        {
          id: college.id,
          json: {
            name: values.name,
            universityId: universityId, // usually we don't change univ, but schema might need it
          },
        },
        options,
      );
    } else {
      createMutation.mutate(
        {
          name: values.name,
          universityId: universityId,
        },
        options,
      );
    }
  };

  const isPending = createMutation.isPending || updateMutation.isPending;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle className="text-right">
            {isEditing ? "تعديل بيانات الكلية" : "إضافة كلية جديدة"}
          </DialogTitle>
          <DialogDescription className="text-right">
            {isEditing
              ? "تعديل اسم الكلية."
              : "أضف كلية جديدة تابعة لهذه الجامعة."}
          </DialogDescription>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <FormField
              control={form.control}
              name="name"
              render={({ field }) => (
                <FormItem className="text-right">
                  <FormLabel>اسم الكلية</FormLabel>
                  <FormControl>
                    <Input
                      placeholder="كلية الهندسة"
                      {...field}
                      className="text-right"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <DialogFooter className="flex gap-2 sm:justify-start">
              <Button
                type="submit"
                className="w-full sm:w-auto"
                disabled={isPending}
              >
                {isPending ? "جاري الحفظ..." : "حفظ"}
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => onOpenChange(false)}
              >
                إلغاء
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
